### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by The-Daishogun** [AmirhosseinAyoubi/SearchInGitHub#1]
According to [yarn documentation](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored) ./yarn/cache/* folder should not be committed to the repo

consider adding the folders mentioned in the documentation to your .gitignore file

**Comment by AriaAyoubi** [comment]
> According to [yarn documentation](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored) ./yarn/cache/* folder should not be committed to the repo
> 
> consider adding the folders mentioned in the documentation to your .gitignore file

gitignore modified

**Comment by The-Daishogun** [comment]
Thanks for the fix
